### ISSUE TITLE
ha as an app on rasbian

### ISSUE THREAD

**Issue by lucaera** [tiagofreire-pt/tv_hisense_home_assistant#3]
Hi all, im trying to add my hisense r7 to my ha but i dont know how can i change this:
"
customize:
  active: true
  folder: mosquitto
" 
where do i do this change if my mosquito is installed as an app as well? 

i got already my cert, i added the scripts everythings, i see the script on my ha but once i clicked on everything of the template doesnt work.

I can see the commands on mqtt explorer but if i try to send a command doesnt really work (im not sure if i pubblish correctly)

Thanks

**Comment by tiagofreire-pt** [comment]
> Hi all, im trying to add my hisense r7 to my ha but i dont know how can i change this:
> "
> customize:
> active: true
> folder: mosquitto
> "
> where do i do this change if my mosquito is installed as an app as well?
>

On HA:

Supervisor -> Dashboard -> Mosquitto Broker -> Configuration

**Comment by lucaera** [comment]
i have HQ on rasbian as an app, i dont have the supervisor's menu

**Comment by tiagofreire-pt** [comment]
Check if there is any `/etc/mosquitto/mosquitto.conf` file in your system.

I can't help any further on that kind of non-standard HA installation.

**Comment by lucaera** [comment]
at the end i didnt need to add the customize part, it worked without (probably the cert file was in a wrong location) now is working beautifully only doesnt work the the turn it on. Im trying to figure out how do it by wol. 

Thanks!
