### ISSUE TITLE
Where exactly does this go in home assistant?

### ISSUE THREAD

**Issue by davebeiler** [tiagofreire-pt/tv_hisense_home_assistant#5]
connection hisensemqtt
address TV_IP_ADDRESS_CHANGE_IT_HERE:36669
username hisenseservice
password multimqttservice
clientid HomeAssistant
bridge_cafile /ssl/hisense.crt
bridge_insecure true
bridge_tls_version tlsv1.2
try_private false
start_type automatic
topic +/remoteapp/# both

?

**Comment by davebeiler** [comment]
THERE ARE NO KNOWN_DEVICES.yaml file any more as of 0.94, https://www.home-assistant.io/integrations/device_tracker/

**Comment by meghead** [comment]
RE: THERE ARE NO KNOWN_DEVICES.yaml file any more

Where should the entry go instead?

**Comment by tiagofreire-pt** [comment]
You need to access the following path, having beforehand the Samba add-on installed on your Home Assistant instance:

    Windows: \\YOUR_HA_LAN_IP\
    Linux: smb://YOUR_HA_LAN_IP/

Put this inside a hisense.conf, in the above path - subfolder /share/mosquitto/. Change only the TV_IP_ADDRESS_CHANGE_IT_HERE, accordingly:

connection hisensemqtt
address TV_IP_ADDRESS_CHANGE_IT_HERE:36669
username hisenseservice
password multimqttservice
clientid HomeAssistant
bridge_cafile /ssl/hisense.crt
bridge_insecure true
bridge_tls_version tlsv1.2
try_private false
start_type automatic
topic +/remoteapp/# both

**Comment by meghead** [comment]
Although I've successfully installed the Samba Share, I'm unable to access the Hisense on it.

I'm getting this in my browser: "Your file couldn’t be accessed, it may have been moved, edited or deleted".

And when I try to map a network drive in windows to my TVs IP I get;; "Windows is unable to communicate with the device"

Could this be because I have set up external access via DuckDNS and SSL? Or perhaps because I also have the "Samba Nas" plugin installed?

**Comment by meghead** [comment]
Samba Share is now working correctly. The source is now showing the correct input in Lovelace/Dashboard.  Pushing the Lovelace buttons sends the corresponding messages to MQTT Explorer. However, nothing is happening on Hisense TV.  Here's the MQTT Explorer data which contains both the RemoteNow app button presses (which work) and the Lovelace button presses (which don't work).;

my ip
remoteapp
mobile
broadcast
platform_service
data
voicetype = { "voice_type": 4 }
actions
ui_service
state = {"statetype":"sourceswitch","sourceid":"HDMI3","sourcename":"HDMI3","is_signal":1,"is_lock":0,"hotel_mode":0,"displayname":"HDMI3"}
data
picturesetting = {"action":"notify_value_changed","menu_id":127,"menu_value_type":"int","menu_value":1}
txtinputdata = {"vkb_status":1,"input_data":"Big Tv"}
hotelmodechange = {"hotel_mode":"off"}
87:f1:ef:9a:d3:4c$vidaa_common
platform_service
data
getdeviceinfo = { "eth0": "a062fb1cd66b", "wlan0": "303235e81ee8", "ip": "my ip", "tv_name": "Big Tv", "voice": "2", "platform": "1", "transport_protocol": "2150", "region": "4", "vidaa_support": "1", "country": "GBR", "language": "eng", "model_name": "65A53FEVS", "tv_version": "V0000.01.00S.L0923" }
getplatformcapbility = [{ "name": "picture_setting", "version": "U4" }, { "name": "volume", "version": "00.00.01" }, { "name": "tv_name", "version": "00.00.01" }, { "name": "booking_list", "version": "00.00.01" }, { "name": "pvr", "version": "00.00.01" }, { "name": "reminder", "version": "00.00.01" }, { "name": "audio_capture", "version": "00.00.01" }, { "name": "screen_capture", "…
gettvinfo = { "brand": "his", "featurecode": "861003009000001000000732", "deviceid": "861003009000001000000732jl4y43aaa4hxwwz2nlg4uo4x6ejnc4gz", "capability": "2021072601", "tuner_num": 1, "fake_sleep": 1, "fake_sleep_state": 1, "audio_capture_supported": 1, "screen_capture_supported": 1, "audio_capture_version": 1 }
ui_service
c0:11:65:fb:af:f4$normal
platform_service
data
getdeviceinfo = { "eth0": "a062fb1cd66b", "wlan0": "303235e81ee8", "ip": "my ip", "tv_name": "Big Tv", "voice": "2", "platform": "1", "transport_protocol": "2150", "region": "4", "vidaa_support": "1", "country": "GBR", "language": "eng", "model_name": "65A53FEVS", "tv_version": "V0000.01.00S.L0923" }
gettvinfo = { "brand": "his", "featurecode": "861003009000001000000732", "deviceid": "861003009000001000000732jl4y43aaa4hxwwz2nlg4uo4x6ejnc4gz", "capability": "2021072601", "tuner_num": 1, "fake_sleep": 1, "fake_sleep_state": 1, "audio_capture_supported": 1, "screen_capture_supported": 1, "audio_capture_version": 1 }
getchannellistinfo = [{ "list_name": "Antenna", "list_para": "slf5b19894-1fe7-4d02-9364-892b96d96e4a", "list_version": "5", "dtv_flag": 1 }]
ui_service
tv
ui_service
46:3f:e0:9d:2b:69$normal
actions
changesource = {"displayname": "HDMI2","hotel_mode": "","isDemo": false,"is_lock": "","is_signal": "","sourceid": "5","sourcename": "HDMI2"}
87:f1:ef:9a:d3:4c$vidaa_common
actions
vidaa_app_connect = {"app_version":2,"connect_result":0}
c0:11:65:fb:af:f4$normal
remote_service
46:3f:e0:9d:2b:69$normal
actions
sendkey = KEY_VOLUMEDOWN
platform_service
87:f1:ef:9a:d3:4c$vidaa_common
actions
gettvinfo
c0:11:65:fb:af:f4$normal
actions
getdeviceinfo
changevolume = 17
mobile
e12712a5-6d9c-4572-8744-a170bf16d7f5
$SYS
broker
connection
HomeAssistant
state = 1

**Comment by tiagofreire-pt** [comment]
Change the TV input with the phone app, while connected with the MQTT Explorer and capture the full command sent by the phone to the TV. Maybe your device has a different argument structure.
